name: delicious_india
description: "A tourism app that can help you find nearest restaurant, find out more about indian food, and even scan to identify indian food using latest AI"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.2
  auto_size_text: ^3.0.0
  camera: ^0.10.5+9
  flutter_vision: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/images/
    - assets/labels.txt
    - assets/yolov8.tflite

  fonts:
    - family: Italiana
      fonts:
        - asset: fonts/Italiana-Regular.ttf